/* eslint-disable react/react-in-jsx-scope */
import { QueryProvider } from './QueryProvider'
import '../styles/globals.css'
import '../styles/devices.min.css'
import { Container } from '~/components/ui/Container'
import Header from '~/components/ui/Header'
import BreadCrumbs from '~/components/ui/BreadCrumbs'
export const metadata = {
  title: 'YingCholocate',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh">
      <body>
        <div id="app">
          <div id="app-container">
            <QueryProvider>
              <Container className="flex items-center mt-10">
                <Header />
              </Container>
              <BreadCrumbs />
              {children}
            </QueryProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
