/* eslint-disable react/react-in-jsx-scope */
import { QueryProvider } from './QueryProvider'
import '../styles/globals.css'
import { Container } from '~/components/ui/Container'
import Header from '~/components/ui/Header'
export const metadata = {
  title: 'YingCholocate',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Container className="flex items-center mt-10">
            <Header />
          </Container>
          <Container className="mt-24 md:mt-28">{children}</Container>
        </QueryProvider>
      </body>
    </html>
  )
}
