1:HL["/_next/static/css/481dd6b263de3d83.css",{"as":"style"}]
0:["qItuUN44cLju6scX2Q5wn",[[["",{"children":["not-found",{}]},"$undefined","$undefined",true],"$L2",[[["$","link","0",{"rel":"stylesheet","href":"/_next/static/css/481dd6b263de3d83.css","precedence":"next"}]],"$L3"]]]]
4:I{"id":2468,"chunks":["861:static/chunks/861-c57997439de199d7.js","776:static/chunks/776-c3f04d838997e498.js","185:static/chunks/app/layout-f2a383e75bb5f2cd.js"],"name":"QueryProvider","async":false}
5:I{"id":8870,"chunks":["861:static/chunks/861-c57997439de199d7.js","776:static/chunks/776-c3f04d838997e498.js","185:static/chunks/app/layout-f2a383e75bb5f2cd.js"],"name":"Container","async":false}
6:I{"id":8011,"chunks":["861:static/chunks/861-c57997439de199d7.js","776:static/chunks/776-c3f04d838997e498.js","185:static/chunks/app/layout-f2a383e75bb5f2cd.js"],"name":"","async":false}
7:I{"id":7626,"chunks":["160:static/chunks/app/not-found-7b9bb25a34c63cd5.js"],"name":"","async":false}
3:[["$","meta","0",{"charSet":"utf-8"}],["$","title","1",{"children":"YingCholocate"}],["$","meta","2",{"name":"description","content":"Generated by Next.js"}],["$","meta","3",{"name":"viewport","content":"width=device-width, initial-scale=1"}]]
2:[["$","html",null,{"lang":"zh","children":["$","body",null,{"children":["$","$L4",null,{"children":[["$","$L5",null,{"className":"flex items-center mt-10","children":["$","$L6",null,{}]}],["$","$L5",null,{"className":"mt-24 md:mt-28","children":[["$","meta",null,{"name":"robots","content":"noindex"}],false,[],["$","$L7",null,{}]]}]]}]}]}],null]
